version: '3'

# chmod ugo+rw dualsubcache.db

services:
  rashpile-translate-api:
    image: registry.${SERVER_URL}/dualsubserver
    container_name: rashpile-translate-api
    labels:
      com.centurylinklabs.watchtower.enable: true
      reproxy.server: "tr.${SERVER_URL}"
      reproxy.route: '^/(.*)'
      reproxy.dest: '/@1'
      reproxy.port: 8989
    volumes:
      - /home/pkoptilin/.keys/googletranslate1:/home/nonroot/.keys/googletranslate1
      - /home/pkoptilin/.keys/deepl1:/home/nonroot/.keys/deepltranslate1
      - /home/pkoptilin/docker/dualsub/api.dualsub.xyz.crt:/dualsub.crt
      - /home/pkoptilin/docker/dualsub/api.dualsub.xyz.key:/dualsub.key
      - /home/pkoptilin/dualsubcache.db:/home/nonroot/dualsubcache.db
    environment:
      - API_KEY=1978-0306-1234
    command: -port=8989
networks:
  default:
    external:
      name: reproxy
