version: '3'

services:
  nodejs:
    image: registry.rashpile.com/blog-example
    container_name: blogjs
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - VIRTUAL_HOST=blog.${SERVER_URL}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=blog.${SERVER_URL}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
networks:
  default:
    external:
      name: nginx-proxy
