version: '3'

services:
  nodejs:
    image: registry.${SERVER_URL}/${SITE}-site
    container_name: ${SITE}
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      reproxy.server: "${SITE}.${SERVER_URL}"
      reproxy.route: '^/(.*)'
      reproxy.dest: '/@1'
      reproxy.port: 80

networks:
  default:
    external:
      name: reproxy
