version: '3.7'

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ${DOCKER_CONFIG_FILE}:/config.json
    restart: always
    ports:
      - 8088:8080
    environment:
      - REPO_USER=${REPO_USER}
      - REPO_PASS=${REPO_PASS}
      # Update containers that have a com.centurylinklabs.watchtower.enable label set to true.
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_DEBUG=true
      # - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}
      # - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_POLL_INTERVAL=60
        # - WATCHTOWER_HTTP_API=true
        # - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}
        # - VIRTUAL_HOST=watchtower.${SERVER_URL}
        # - VIRTUAL_PORT=8080
        # - LETSENCRYPT_HOST=watchtower.${SERVER_URL}
        # - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
  
networks:
  default:
    external:
      name: nginx-proxy
