version: '3'
# UPSTREAM_PORT=9080 UPSTREAM_HOST=$(hostname -I | awk '{print $1}') docker compose -f ./docker-compose-local.yml up
services:
  local-dev:
    build: ./resources/local-dev/
    ports:
      - 8080
    environment:
      - UPSTREAM_HOST=${UPSTREAM_HOST:-host.docker.internal}
      - UPSTREAM_PORT=${UPSTREAM_PORT:-9080}
    labels:
      reproxy.server: "local.${SERVER_URL}"
      reproxy.route: '^/(.*)'
      reproxy.dest: '/@1'
      reproxy.port: 8080
networks:
  default:
    external:
      name: reproxy

