version: '3.7'
#
#
#

services:
  registry:
    container_name: registry
    image: registry:2
    volumes:
      - /var/lib/registry:/var/lib/registry
      - ./auth:/auth
    # ports:
    #   - 5000:5000
    restart: always
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      # - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.rashpile.com.crt
      # - REGISTRY_HTTP_TLS_KEY=/certs/registry.rashpile.com.key
      - VIRTUAL_HOST=registry.${SERVER_URL}
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=registry.${SERVER_URL}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
volumes:
  certs:
networks:
  default:
    external:
      name: nginx-proxy
