version: '3.7'
#
#
#

services:
  registry:
    container_name: registry
    image: registry:2
    volumes:
      - /var/lib/registry:/var/lib/registry
      - ./auth:/auth
    # ports:
    #   - 5000:5000
    restart: always
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
    labels:
      reproxy.server: "registry.${SERVER_URL}"
      reproxy.route: '^/(.*)'
      reproxy.dest: '/@1'
      reproxy.port: 5000
volumes:
  certs:
networks:
  default:
    external:
      name: reproxy
