version: '3'

services:
  rashpile-api:
    image: registry.rashpile.com/rashpile-api
    container_name: rashpile-api
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - VIRTUAL_HOST=api.${SERVER_URL}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=api.${SERVER_URL}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
networks:
  default:
    external:
      name: nginx-proxy
