version: '3'

# mkdir -p ~/.code-server-config
services:
  codeserver:
    container_name: codeserver
    image: codercom/code-server:latest
    restart: always
    # ports:
    #   - 8080:8080
    user: $DOCKER_USER
    environment:
      - DOCKER_USER=$USER
    volumes:
      - ${HOME}/.code-server-config:/home/coder/.config
      - ${CODE_SERVER_PATH}:/home/coder/project
    command: --disable-telemetry /home/coder/project
    labels:
      reproxy.server: "code.${SERVER_URL}"
      reproxy.route: '^/(.*)'
      reproxy.dest: '/@1'
      reproxy.port: 8080


networks:
  default:
    external:
      name: reproxy
