version: '3'

services:
  nodejs:
    image: registry.rashpile.com/blog-example
    container_name: blogjs
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - VIRTUAL_HOST=blog.rashpile.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=blog.rashpile.com
      - LETSENCRYPT_EMAIL=koptilin@gmail.com
networks:
  default:
    external:
      name: nginx-proxy
