version: '3'

services:
  nodejs:
    image: registry.rashpile.com/${SITE}-site
    container_name: ${SITE}
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - VIRTUAL_HOST=${SITE}.${SERVER_URL}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${SITE}.${SERVER_URL}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
networks:
  default:
    external:
      name: nginx-proxy
